### ISSUE TITLE
Allow Configuration For Filtering By Source

### ISSUE THREAD

**Issue by DonSeannelly** [Cyber4All/database-interaction#8]
### Request
The suggestion service should accept a configuration parameter that can inform the service to only emit standards on the web-socket if they come from the desired source. 

### What Are Sources
The source would be NCWF, CAE, etc...

### Use Case
This is needed for the cube to be able to limit the overwhelming number of standards that might be suggested when filling out the form to search learning objects by their respective mappings.

**Comment by ksherb1** [comment]
This is done; I'm in the process of redeploying docker and then I'll push the edits here. The suggestOutcomes event will now have an additional parameter, `filter`, which is an object mapping the properties in an outcome suggestion to strings, which must be _contained within_ the value for the corresponding parameter of the outcome suggestion.

NOTE: I have decided to keep using the property name "author" for what we're now calling "source", because it is more consistent with how the property names in the database are used. When you display it client-side, you should be using the term "Source", but your filter object will need an "author" parameter.

NOTE: this lets you filter by date and name just as well as source

NOTE: Right now there are two "authors" for NCWF. Filtering {author:"NCWF"} will give you both KSA's (author==="NCWF") and tasks (author==="NCWF Tasks"), which is appropriate. But we may want to change the KSA "author" to "NCWF KSAs" so that users may narrow the field further.
